import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/reset.css";
import "./styles/colors.css";
import "./styles/globals.css";
import { StoreProvider } from "./StoreProvider";
import { Provider } from "react-redux";
import { AppContextProvider } from "./AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
           <body className={inter.className}>{children}</body>
       </StoreProvider>
    </html>
  );
}
